[project]
name = "obsidian-insights"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = [
    "dlt>=1.5.0",
    "duckdb>=1.1.3",
    "enlighten>=1.13.0",
    "sqlmesh[github,web]>=0.150.1",
]
