name: SQLMesh CI/CD Bot
run-name: 🚀SQLMesh CI/CD Bot 🚀
on:
  workflow_dispatch:
  pull_request:
    types:
      - synchronize
      - opened
  pull_request_review:
    types:
    - edited
    - submitted
    - dismissed
# The latest commit is the one that will be used to create the PR environment and deploy to production
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  sqlmesh:
    name: SQLMesh Actions Workflow
    runs-on: ubuntu-latest
    permissions:
      # Required to access code in PR
      contents: write
      # Required to post comments
      issues: write
      # Required to update check runs
      checks: write
      # Required to merge
      pull-requests: write
    env:
      motherduck_token: ${{ secrets.motherduck_token }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.pull_request && github.event.issue.number || github.event.pull_request.number  }}/merge
      - name: Install UV
        run: pip install uv
        shell: bash
      - name: Run CI/CD Bot
        run: |
          uv run sqlmesh_cicd -p ${{ github.workspace }} github --token ${{ secrets.GITHUB_TOKEN }} run-all
        shell: bash
