name: SQLMesh ELT Bot
run-name: 🚀SQLMesh ELT Bot 🚀
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  sqlmesh:
    name: SQLMesh Actions Workflow
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      motherduck_token: ${{ secrets.motherduck_token }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Install UV
        run: pip install uv
        shell: bash
      - name: Extract & Load
        run: |
          uv run ./pipelines/northwind.py
        shell: bash
      - name: Transform
        run: |
          uv run sqlmesh run prod
        shell: bash